#:schema https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json

version = 3
final_space = true
console_title_template = '{{ .Shell }} in {{ .Folder }}'

# Left Block

[[blocks]]
type = 'prompt'
alignment = 'left'
newline = true

[[blocks.segments]]
type = 'path'
style = 'plain'
template = '{{ .Path }}'
background = 'transparent'
foreground = 'blue'

[blocks.segments.properties]
style = 'full'

[[blocks.segments]]
type = 'git'
style = 'plain'
template = ' {{ .HEAD }}{{ if or (.Working.Changed) (.Staging.Changed) }}*{{ end }} <cyan>{{ if gt .Behind 0 }}⇣{{ end }}{{ if gt .Ahead 0 }}⇡{{ end }}</>'
background = 'transparent'
foreground = '#6c6c6c'

[blocks.segments.properties]
branch_icon = ''
commit_icon = '@'
fetch_status = true

# Right Block

[[blocks]]
type = 'rprompt'
overflow = 'hidden'

[[blocks.segments]]
type = 'executiontime'
style = 'plain'
template = '{{ .FormattedMs }}'
background = 'transparent'
foreground = 'yellow'

[blocks.segments.properties]
threshold = 5000
style = 'round'

# Prompt Block

[[blocks]]
type = 'prompt'
alignment = 'left'
newline = true

[[blocks.segments]]
type = 'text'
style = 'plain'
template = '{{ if eq .Code 0 }}➜{{ else }}✘{{ end }}'
background = 'transparent'
foreground_templates = [
  '{{if gt .Code 0}}red{{end}}',
  '{{if eq .Code 0}}magenta{{end}}',
]

[transient_prompt]
template = '{{ if eq .Code 0 }}➜ {{ else }}✘ {{ end }}'
background = 'transparent'
foreground_templates = [
  '{{if gt .Code 0}}red{{end}}',
  '{{if eq .Code 0}}magenta{{end}}',
]

[secondary_prompt]
template = '• '
background = 'transparent'
foreground = 'magenta'
